name: build image docker

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Image
      run: 
          echo "${{ secrets.DOCKERPW }}" | docker login -u "sabirlkhaloufi" --password-stdin
          docker image build . -t sabirlkhaloufi/test:latest
    - name: push image
      run : docker push sabirlkhaloufi/test:latest    
  