name: build image docker

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login -username=sabirlkhaloufi --password=${{ secrets.DOCKERPW }}
        docker image build . -t sabirlkhaloufi/test:latest
        docker push sabirlkhaloufi/test:latest