name: build image docker

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build && push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "sabirlkhaloufi" --password-stdin
        docker image build . -t sabirlkhaloufi/bettal:latest
        docker push sabirlkhaloufi/bettal:latest
  